// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20260418213444_SeedFaq")]
    partial class SeedFaq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ContactRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ContactRequests", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.FaqEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No, GymPro is designed for all fitness levels. Our trainers guide beginners with proper techniques and structured workout plans to help them start safely and confidently.",
                            Title = "Q1. Do I need prior gym experience to join CoreFitness?"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Our membership gives you full access to state-of-the-art gym equipment, free weights, cardio machines, and functional training areas. You can also enjoy group fitness classes, locker rooms, and relaxation areas designed to support your overall fitness experience.",
                            Title = "Q2. What facilities are included with the membership?"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Yes, we offer trial sessions so you can explore our facilities and experience our training environment before committing. This allows you to meet our trainers, test the equipment, and see if CoreFitness is the right fit for you.",
                            Title = "Q3. Can I try the gym before taking a membership?"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Absolutely! We offer a variety of group workout programs, including strength training, cardio sessions, yoga, and high-intensity interval training. These classes are led by experienced instructors and are suitable for all fitness levels.",
                            Title = "Q4. Are there group workout programs available?"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Yes, many of our programs include basic nutrition guidance to help you reach your fitness goals. Our trainers can provide recommendations and tips to support a balanced diet alongside your workout routine.",
                            Title = "Q5. Is nutrition guidance included in the plans?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
